### ISSUE TITLE
Login page submit behavior

### ISSUE THREAD

**Issue by PeterDaveHello** [nfsnfs/COSCUP-System-frontend#5]
On the login page, https://staff.coscup.org/#login, `Enter` on the keybaord can not lead to submit the form, should do.

**Comment by nfsnfs** [comment]
Thank you so much ... :+1: 
I'm not so familiar with JavaScript ... :(

**Comment by PeterDaveHello** [comment]
hmmmm ... me neither

**Comment by PeterDaveHello** [comment]
hmmmm ... no work at all, @nfsnfs could you reopen this?

**Comment by nfsnfs** [comment]
187d25da83423e5b95a9b7569c289d4c5b633048
I think it's fixed now.
